### ISSUE TITLE
Cannot use geoip-def-americas.nft

### ISSUE THREAD

**Issue by keebs** [pvxe/nftables-geoip#8] opened 2024-01-22 15:58 UTC
After including "geoip-def-all.nft", "geoip-ipv4.nft", and "geoip-ipv6.nft", all nft commands take about 15s to process. I was trying to replace "geoip-def-all.nft" with "geoip-def-americas.nft" to improve this timeframe, but "geoip-ipv4.nft" & "geoip-ipv6.nft" require the "geoip-def-all.nft" file to load. Am I missing some way to generate the ipv4 and ipv6 files for the regional nft files?

Or is there some other way to improve the nft response time after loading the "geoip-def-all.nft" file? I am not limited by cpu or memory. TY

**Comment by pvxe** [comment] 2024-01-24 15:00
I cannot reproduce this right now but if you need only a little subset of countries you can use `-c/--country-filter` to generate a smaller map of countries and addresses.

To use a smaller `*def-*.nft` file the only solution as of now is to create it manually with the necessary `define ...` lines and using
it in your main nft file.

**Comment by keebs** [comment] 2024-01-24 15:50
If I generate a US subset, I can now use the geoip-def-americas.nft file instead of geoip-def-all.nft. This also reduced my nft response times from 15s to 2s. Thanks!

**Comment by pvxe** [comment] 2024-01-24 17:07
Nice! Closing this now.

**Closed by pvxe** 2024-01-24 17:07 UTC
